spring.application.name=AnomalyDetection
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}
spring.profiles.active=local
spring.jwt.secret=${APP_JWT_SECRET}